### ISSUE TITLE
挺不错的，还有些问题问一下

### ISSUE THREAD

**Issue by MisterClown** [meiniepan/Pic2Ascii#4]
看你简介里贴的图片是彩色，我生成的ascii图片怎么没有颜色？

**Comment by MisterClown** [comment]
好多图片，有些地方直接就空白了，是图片太大，还是颜色或者压缩的问题？

**Comment by meiniepan** [comment]
彩色的是电脑端的效果，这个项目没有颜色，空白的话应该是image展示时候centercrop,你保存到本地看原图就可以了

**Comment by meiniepan** [comment]
彩色的已经有了，下新APP可体验
