### ISSUE TITLE
图片保存的问题

### ISSUE THREAD

**Issue by wanghao15536870732** [meiniepan/Pic2Ascii#5]
确实保存到手机里面了，但是为啥相册里面没有？

**Comment by meiniepan** [comment]
我的小米手机可以检测到保存的图片，存放路径不是显示了吗，手动找一下

**Comment by wanghao15536870732** [comment]
华为荣耀八，发现手机储存没有这个目录

|||
|:--:|:--:|
|![Screenshot_20180909-180607.png](https://upload-images.jianshu.io/upload_images/9140378-70545d8cbe6afaba.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/240)|![Screenshot_20180909-180601.png](https://upload-images.jianshu.io/upload_images/9140378-b908a10b02e540d4.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/240)|

**Comment by meiniepan** [comment]
内部存储下有个meiniepan文件夹

**Comment by wanghao15536870732** [comment]
应该是我的相册没有刷新出来:(
